# Site
name: "Francisco Rodrigues"
description: ""
meta_description: "Site de Francisco Rodrigues."
logo: 'https://s.gravatar.com/avatar/00b0cb1733b78abedc8c31283176dd7b?s=400'
favicon: 'https://s.gravatar.com/avatar/00b0cb1733b78abedc8c31283176dd7b'
baseurl: /mediumish-theme-jekyll
# google_analytics: 'UA-46278016-1'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

defaults:
  - scope:
      path: ""
    values:      
      show_explorer: true
      comments: false
toc:   
  min_level: 2 # default: 1
  max_level: 5 # default: 6

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-menus
  - jekyll-toc
collections:
  projetos:
    output: true
    permalink: '/:collection/:path/'
    tags:
      - projeto pesquisa
    categories: 
      - projeto pesquisa

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 10
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge