# Site
baseurl: /mediumish-theme-jekyll
# seo

name: "Francisco Rodrigues"
description: ""
meta_description: "Site de Francisco Rodrigues."
logo: 'https://s.gravatar.com/avatar/00b0cb1733b78abedc8c31283176dd7b?s=400'
favicon: 'https://s.gravatar.com/avatar/00b0cb1733b78abedc8c31283176dd7b'
twitter:
  username: frchico
  card: summary
lang: pt-BR

# google_analytics: 'UA-46278016-1'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

defaults:
  - scope:
      path: ""
    values:
      show_explorer: true
      comments: false
toc:   
  min_level: 2 # default: 1
  max_level: 5 # default: 6

tag_page_layout: tag_page
tag_page_dir: tag
tag_feed_layout: tag_feed
tag_feed_dir: tag
tag_page_data:
  sitemap: false
tag_permalink_style: pretty

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-menus
  - jekyll-toc
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - jekyll-minifier
  - jekyll-gzip
  # - jekyll-admin
  
collections:
  projetos:
    output: true
    permalink: '/:collection/:path/'
    tags:
      - projeto pesquisa
    categories: 
      - projeto pesquisa

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 10
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge


# # assets
# compression: true
# defaults:
#   js: { integrity: true } # true on JEKYLL_ENV=production
#   css: { integrity: true } # true on JEKYLL_ENV=production
#   img: { integrity: true } # true on JEKYLL_ENV=production


# jekyll-minifier:
#   preserve_php: true                # Default: false
#   remove_spaces_inside_tags: true   # Default: true
#   remove_multi_spaces: true         # Default: true
#   remove_comments: true             # Default: true
#   remove_intertag_spaces: true      # Default: false
#   remove_quotes: false              # Default: false
#   compress_css: true                # Default: true
#   compress_javascript: true         # Default: true
#   compress_json: true               # Default: true
#   simple_doctype: false             # Default: false
#   remove_script_attributes: false   # Default: false
#   remove_style_attributes: false    # Default: false
#   remove_link_attributes: false     # Default: false
#   remove_form_attributes: false     # Default: false
#   remove_input_attributes: false    # Default: false
#   remove_javascript_protocol: false # Default: false
#   remove_http_protocol: false       # Default: false
#   remove_https_protocol: false      # Default: false
#   preserve_line_breaks: false       # Default: false
#   simple_boolean_attributes: false  # Default: false
#   compress_js_templates: false      # Default: false
#   preserve_patterns:                # Default: (empty)
#   uglifier_args:                    # Default: (empty)