#!/usr/bin/env bash
set -e # halt script on error
#gem install bundler
#bundle install
#bundle update
bundle exec jekyll build JEKYLL_ENV=production
#bundle exec htmlproofer ./_site --disable-external
touch ./_site/.nojekyll # this file tells gh-pages that there is no need to build